<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                'order' => 10,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 11,
            ),
            10 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 12,
            ),
            11 => 
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            14 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            15 => 
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            17 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            18 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            21 => 
            array (
                'id' => 56,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 57,
                'data_type_id' => 7,
                'field' => 'item_code',
                'type' => 'text',
                'display_name' => 'item_code',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 58,
                'data_type_id' => 7,
                'field' => 'item_name',
                'type' => 'text',
                'display_name' => 'Nama Barang',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            24 => 
            array (
                'id' => 59,
                'data_type_id' => 7,
                'field' => 'item_quantity',
                'type' => 'text',
                'display_name' => 'Quantity',
                'required' => 0,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            25 => 
            array (
                'id' => 60,
                'data_type_id' => 7,
                'field' => 'item_base_unit_1_id',
                'type' => 'select_dropdown',
                'display_name' => 'Satuan 1',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            26 => 
            array (
                'id' => 61,
                'data_type_id' => 7,
                'field' => 'item_base_unit_2_id',
                'type' => 'text',
                'display_name' => 'Satuan 2',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            27 => 
            array (
                'id' => 62,
                'data_type_id' => 7,
                'field' => 'base_1_to_base_2',
                'type' => 'text',
                'display_name' => 'Konversi',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            28 => 
            array (
                'id' => 63,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            29 => 
            array (
                'id' => 64,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 1,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            30 => 
            array (
                'id' => 65,
                'data_type_id' => 7,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            31 => 
            array (
                'id' => 66,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            32 => 
            array (
                'id' => 67,
                'data_type_id' => 8,
                'field' => 'base_unit_name',
                'type' => 'text',
                'display_name' => 'Base Unit Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            33 => 
            array (
                'id' => 68,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            34 => 
            array (
                'id' => 69,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            35 => 
            array (
                'id' => 70,
                'data_type_id' => 8,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            36 => 
            array (
                'id' => 116,
                'data_type_id' => 7,
                'field' => 'item_belongsto_item_base_unit_relationship',
                'type' => 'relationship',
                'display_name' => 'Satuan',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Model\\\\ItemBaseUnit","table":"item_base_units","type":"belongsTo","column":"item_base_unit_1_id","key":"id","label":"base_unit_name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 12,
            ),
            37 => 
            array (
                'id' => 117,
                'data_type_id' => 7,
                'field' => 'item_belongsto_item_base_unit_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Satuan 2',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Model\\\\ItemBaseUnit","table":"item_base_units","type":"belongsTo","column":"item_base_unit_2_id","key":"id","label":"base_unit_name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 13,
            ),
            38 => 
            array (
                'id' => 129,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            39 => 
            array (
                'id' => 130,
                'data_type_id' => 13,
                'field' => 'document_no',
                'type' => 'text',
                'display_name' => 'Nomor DO',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
            'details' => '{"display":{"width":"6"},"validation":{"rule":"required|unique:sales_headers,document_no","messages":{"required":":attribute tidak boleh kosong.","unique":":attribute sudah ada (Duplikat)"}}}',
                'order' => 2,
            ),
            40 => 
            array (
                'id' => 131,
                'data_type_id' => 13,
                'field' => 'document_date',
                'type' => 'date',
                'display_name' => 'Tanggal DO',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 3,
            ),
            41 => 
            array (
                'id' => 132,
                'data_type_id' => 13,
                'field' => 'document_memo',
                'type' => 'text_area',
                'display_name' => 'Memo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 5,
            ),
            42 => 
            array (
                'id' => 133,
                'data_type_id' => 13,
                'field' => 'document_memo_2',
                'type' => 'text_area',
                'display_name' => 'Note DO',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 4,
            ),
            43 => 
            array (
                'id' => 134,
                'data_type_id' => 13,
                'field' => 'external_document',
                'type' => 'text',
                'display_name' => 'Dokumen Eksternal',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 6,
            ),
            44 => 
            array (
                'id' => 135,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            45 => 
            array (
                'id' => 136,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            46 => 
            array (
                'id' => 137,
                'data_type_id' => 13,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            47 => 
            array (
                'id' => 138,
                'data_type_id' => 14,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            48 => 
            array (
                'id' => 140,
                'data_type_id' => 14,
                'field' => 'document_no',
                'type' => 'text',
                'display_name' => 'Document No',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            49 => 
            array (
                'id' => 141,
                'data_type_id' => 14,
                'field' => 'item_id',
                'type' => 'text',
                'display_name' => 'Item Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            50 => 
            array (
                'id' => 142,
                'data_type_id' => 14,
                'field' => 'item_code',
                'type' => 'text',
                'display_name' => 'Item Code',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            51 => 
            array (
                'id' => 143,
                'data_type_id' => 14,
                'field' => 'item_name',
                'type' => 'text',
                'display_name' => 'Item Name',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            52 => 
            array (
                'id' => 144,
                'data_type_id' => 14,
                'field' => 'quantity',
                'type' => 'number',
                'display_name' => 'Quantity',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"5"}}',
                'order' => 9,
            ),
            53 => 
            array (
                'id' => 145,
                'data_type_id' => 14,
                'field' => 'item_base_unit_id',
                'type' => 'text',
                'display_name' => 'Item Base Unit Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            54 => 
            array (
                'id' => 146,
                'data_type_id' => 14,
                'field' => 'item_base_unit',
                'type' => 'text',
                'display_name' => 'Item Base Unit',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            55 => 
            array (
                'id' => 147,
                'data_type_id' => 14,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            56 => 
            array (
                'id' => 148,
                'data_type_id' => 14,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            57 => 
            array (
                'id' => 149,
                'data_type_id' => 14,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            58 => 
            array (
                'id' => 150,
                'data_type_id' => 14,
                'field' => 'sales_detail_belongsto_item_relationship',
                'type' => 'relationship',
                'display_name' => 'Nama Barang',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"},"model":"App\\\\Model\\\\Item","table":"items","type":"belongsTo","column":"item_id","key":"id","label":"item_name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            59 => 
            array (
                'id' => 152,
                'data_type_id' => 7,
                'field' => 'item_code_w_variant',
                'type' => 'text',
                'display_name' => 'Kode Barang',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            60 => 
            array (
                'id' => 153,
                'data_type_id' => 14,
                'field' => 'document_header_id',
                'type' => 'text',
                'display_name' => 'Document Header Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            61 => 
            array (
                'id' => 154,
                'data_type_id' => 15,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            62 => 
            array (
                'id' => 155,
                'data_type_id' => 15,
                'field' => 'item_code',
                'type' => 'text',
                'display_name' => 'Kode Barang',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            63 => 
            array (
                'id' => 156,
                'data_type_id' => 15,
                'field' => 'item_name',
                'type' => 'text',
                'display_name' => 'Item Name',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            64 => 
            array (
                'id' => 157,
                'data_type_id' => 15,
                'field' => 'item_id',
                'type' => 'text',
                'display_name' => 'Item Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            65 => 
            array (
                'id' => 158,
                'data_type_id' => 15,
                'field' => 'document_no',
                'type' => 'text',
                'display_name' => 'Document No',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 6,
            ),
            66 => 
            array (
                'id' => 159,
                'data_type_id' => 15,
                'field' => 'document_type_id',
                'type' => 'text',
                'display_name' => 'Document Type Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            67 => 
            array (
                'id' => 160,
                'data_type_id' => 15,
                'field' => 'document_type_name',
                'type' => 'text',
                'display_name' => 'Document Type Name',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            68 => 
            array (
                'id' => 161,
                'data_type_id' => 15,
                'field' => 'document_id',
                'type' => 'text',
                'display_name' => 'Document Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            69 => 
            array (
                'id' => 162,
                'data_type_id' => 15,
                'field' => 'location_code',
                'type' => 'text',
                'display_name' => 'Location Code',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            70 => 
            array (
                'id' => 163,
                'data_type_id' => 15,
                'field' => 'quantity',
                'type' => 'text',
                'display_name' => 'Quantity',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 11,
            ),
            71 => 
            array (
                'id' => 164,
                'data_type_id' => 15,
                'field' => 'reconciled',
                'type' => 'text',
                'display_name' => 'Reconciled',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            72 => 
            array (
                'id' => 165,
                'data_type_id' => 15,
                'field' => 'reconciled_id',
                'type' => 'text',
                'display_name' => 'Reconciled Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            73 => 
            array (
                'id' => 166,
                'data_type_id' => 15,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            74 => 
            array (
                'id' => 167,
                'data_type_id' => 15,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            75 => 
            array (
                'id' => 168,
                'data_type_id' => 15,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            76 => 
            array (
                'id' => 169,
                'data_type_id' => 14,
                'field' => 'sales_detail_belongsto_item_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Kode Barang',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Model\\\\Item","table":"items","type":"belongsTo","column":"item_id","key":"id","label":"item_code_w_variant","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            77 => 
            array (
                'id' => 170,
                'data_type_id' => 16,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            78 => 
            array (
                'id' => 171,
                'data_type_id' => 16,
                'field' => 'document_header_id',
                'type' => 'text',
                'display_name' => 'Document Header Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            79 => 
            array (
                'id' => 172,
                'data_type_id' => 16,
                'field' => 'document_no',
                'type' => 'text',
                'display_name' => 'Document No',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            80 => 
            array (
                'id' => 173,
                'data_type_id' => 16,
                'field' => 'item_id',
                'type' => 'text',
                'display_name' => 'Item Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            81 => 
            array (
                'id' => 174,
                'data_type_id' => 16,
                'field' => 'item_code',
                'type' => 'text',
                'display_name' => 'Item Code',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            82 => 
            array (
                'id' => 175,
                'data_type_id' => 16,
                'field' => 'item_name',
                'type' => 'text',
                'display_name' => 'Item Name',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            83 => 
            array (
                'id' => 176,
                'data_type_id' => 16,
                'field' => 'quantity',
                'type' => 'number',
                'display_name' => 'Quantity',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"5"}}',
                'order' => 9,
            ),
            84 => 
            array (
                'id' => 177,
                'data_type_id' => 16,
                'field' => 'item_base_unit_id',
                'type' => 'text',
                'display_name' => 'Item Base Unit Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            85 => 
            array (
                'id' => 178,
                'data_type_id' => 16,
                'field' => 'item_base_unit',
                'type' => 'text',
                'display_name' => 'Item Base Unit',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            86 => 
            array (
                'id' => 179,
                'data_type_id' => 16,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            87 => 
            array (
                'id' => 180,
                'data_type_id' => 16,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            88 => 
            array (
                'id' => 181,
                'data_type_id' => 16,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            89 => 
            array (
                'id' => 182,
                'data_type_id' => 17,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            90 => 
            array (
                'id' => 183,
                'data_type_id' => 17,
                'field' => 'document_no',
                'type' => 'text',
                'display_name' => 'Nomor Surat Jalan Pembelian',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
            'details' => '{"display":{"width":"6"},"validation":{"rule":"required|unique:purchase_headers,document_no","messages":{"required":":attribute tidak boleh kosong.","unique":":attribute sudah ada (Duplikat)"}}}',
                'order' => 2,
            ),
            91 => 
            array (
                'id' => 184,
                'data_type_id' => 17,
                'field' => 'document_date',
                'type' => 'date',
                'display_name' => 'Tanggal Barang Masuk',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 4,
            ),
            92 => 
            array (
                'id' => 185,
                'data_type_id' => 17,
                'field' => 'document_memo',
                'type' => 'text_area',
                'display_name' => 'Memo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 5,
            ),
            93 => 
            array (
                'id' => 186,
                'data_type_id' => 17,
                'field' => 'document_memo_2',
                'type' => 'text',
                'display_name' => 'Document Memo 2',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            94 => 
            array (
                'id' => 187,
                'data_type_id' => 17,
                'field' => 'external_document',
                'type' => 'text',
                'display_name' => 'Nomor BP',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 3,
            ),
            95 => 
            array (
                'id' => 188,
                'data_type_id' => 17,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            96 => 
            array (
                'id' => 189,
                'data_type_id' => 17,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            97 => 
            array (
                'id' => 190,
                'data_type_id' => 17,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            98 => 
            array (
                'id' => 191,
                'data_type_id' => 16,
                'field' => 'purchase_detail_belongsto_item_relationship',
                'type' => 'relationship',
                'display_name' => 'Nama Barang',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"},"model":"App\\\\Model\\\\Item","table":"items","type":"belongsTo","column":"item_id","key":"id","label":"item_name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            99 => 
            array (
                'id' => 192,
                'data_type_id' => 16,
                'field' => 'purchase_detail_belongsto_item_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Kode Barang',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Model\\\\Item","table":"items","type":"belongsTo","column":"item_id","key":"id","label":"item_code_w_variant","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            100 => 
            array (
                'id' => 193,
                'data_type_id' => 15,
                'field' => 'date',
                'type' => 'date',
                'display_name' => 'Tanggal',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            101 => 
            array (
                'id' => 194,
                'data_type_id' => 18,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            102 => 
            array (
                'id' => 195,
                'data_type_id' => 18,
                'field' => 'document_no',
                'type' => 'text',
                'display_name' => 'Nomor Retur',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
            'details' => '{"display":{"width":"6"},"validation":{"rule":"required|unique:sales_return_headers,document_no","messages":{"required":":attribute tidak boleh kosong.","unique":":attribute sudah ada (Duplikat)"}}}',
                'order' => 2,
            ),
            103 => 
            array (
                'id' => 196,
                'data_type_id' => 18,
                'field' => 'document_date',
                'type' => 'date',
                'display_name' => 'Tanggal Retur',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 3,
            ),
            104 => 
            array (
                'id' => 197,
                'data_type_id' => 18,
                'field' => 'document_memo',
                'type' => 'text_area',
                'display_name' => 'Memo Retur',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 5,
            ),
            105 => 
            array (
                'id' => 198,
                'data_type_id' => 18,
                'field' => 'document_memo_2',
                'type' => 'text',
                'display_name' => 'Document Memo 2',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            106 => 
            array (
                'id' => 199,
                'data_type_id' => 18,
                'field' => 'external_document',
                'type' => 'text',
                'display_name' => 'Nomor Nota',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 4,
            ),
            107 => 
            array (
                'id' => 200,
                'data_type_id' => 18,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            108 => 
            array (
                'id' => 201,
                'data_type_id' => 18,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            109 => 
            array (
                'id' => 202,
                'data_type_id' => 18,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            110 => 
            array (
                'id' => 203,
                'data_type_id' => 19,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            111 => 
            array (
                'id' => 204,
                'data_type_id' => 19,
                'field' => 'document_header_id',
                'type' => 'text',
                'display_name' => 'Document Header Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            112 => 
            array (
                'id' => 205,
                'data_type_id' => 19,
                'field' => 'document_no',
                'type' => 'text',
                'display_name' => 'Document No',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            113 => 
            array (
                'id' => 206,
                'data_type_id' => 19,
                'field' => 'item_id',
                'type' => 'text',
                'display_name' => 'Item Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            114 => 
            array (
                'id' => 207,
                'data_type_id' => 19,
                'field' => 'item_code',
                'type' => 'text',
                'display_name' => 'Item Code',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            115 => 
            array (
                'id' => 208,
                'data_type_id' => 19,
                'field' => 'item_name',
                'type' => 'text',
                'display_name' => 'Item Name',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            116 => 
            array (
                'id' => 209,
                'data_type_id' => 19,
                'field' => 'quantity',
                'type' => 'text',
                'display_name' => 'Quantity',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"5"}}',
                'order' => 9,
            ),
            117 => 
            array (
                'id' => 210,
                'data_type_id' => 19,
                'field' => 'item_base_unit_id',
                'type' => 'text',
                'display_name' => 'Item Base Unit Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            118 => 
            array (
                'id' => 211,
                'data_type_id' => 19,
                'field' => 'item_base_unit',
                'type' => 'text',
                'display_name' => 'Item Base Unit',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            119 => 
            array (
                'id' => 212,
                'data_type_id' => 19,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            120 => 
            array (
                'id' => 213,
                'data_type_id' => 19,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            121 => 
            array (
                'id' => 214,
                'data_type_id' => 19,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            122 => 
            array (
                'id' => 215,
                'data_type_id' => 19,
                'field' => 'sales_return_detail_belongsto_item_relationship',
                'type' => 'relationship',
                'display_name' => 'Nama Barang',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"},"model":"App\\\\Model\\\\Item","table":"items","type":"belongsTo","column":"item_id","key":"id","label":"item_name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            123 => 
            array (
                'id' => 216,
                'data_type_id' => 19,
                'field' => 'sales_return_detail_belongsto_item_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Kode Barang',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Model\\\\Item","table":"items","type":"belongsTo","column":"item_id","key":"id","label":"item_code_w_variant","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            124 => 
            array (
                'id' => 217,
                'data_type_id' => 15,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            125 => 
            array (
                'id' => 218,
                'data_type_id' => 20,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            126 => 
            array (
                'id' => 219,
                'data_type_id' => 20,
                'field' => 'excel_name',
                'type' => 'text',
                'display_name' => 'Excel Name',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            127 => 
            array (
                'id' => 220,
                'data_type_id' => 20,
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'User Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            128 => 
            array (
                'id' => 221,
                'data_type_id' => 20,
                'field' => 'document_no',
                'type' => 'text',
                'display_name' => 'Document No',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            129 => 
            array (
                'id' => 222,
                'data_type_id' => 20,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            130 => 
            array (
                'id' => 223,
                'data_type_id' => 20,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            131 => 
            array (
                'id' => 224,
                'data_type_id' => 20,
                'field' => 'slug_name',
                'type' => 'text',
                'display_name' => 'Slug Name',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
        ));
        
        
    }
}