<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-17 07:27:42',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-25 07:38:06',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-17 07:27:42',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-17 07:27:42',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-25 07:38:06',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-25 07:38:06',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-25 07:38:06',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-25 07:38:06',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-25 07:38:06',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2020-06-17 07:27:42',
                'updated_at' => '2020-06-25 07:38:06',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Items',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bag',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2020-06-17 07:28:07',
                'updated_at' => '2020-06-26 07:42:53',
                'route' => 'voyager.items.index',
                'parameters' => 'null',
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Item Base Units',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2020-06-17 07:28:15',
                'updated_at' => '2020-06-26 07:43:27',
                'route' => 'voyager.item-base-units.index',
                'parameters' => 'null',
            ),
            12 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Pengeluaran Stok',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-truck',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2020-06-18 04:20:02',
                'updated_at' => '2020-06-26 07:39:14',
                'route' => 'voyager.pengeluaran-stok.index',
                'parameters' => 'null',
            ),
            13 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Pengeluaran Stok Details',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-truck',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2020-06-19 10:40:02',
                'updated_at' => '2020-06-26 07:39:14',
                'route' => 'voyager.pengeluaran-stok-details.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Item Ledger Entries',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-book',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2020-06-24 04:24:28',
                'updated_at' => '2020-06-26 07:43:47',
                'route' => 'voyager.item-ledger-entries.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'SJ Pembelian Detail',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-plus',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 16,
                'created_at' => '2020-06-25 07:26:49',
                'updated_at' => '2020-06-25 07:41:57',
                'route' => 'voyager.sj-pembelian-details.index',
                'parameters' => 'null',
            ),
            16 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'SJ Pembelian',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-plus',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2020-06-25 07:34:51',
                'updated_at' => '2020-06-25 07:38:23',
                'route' => 'voyager.sj-pembelian.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Retur Penjualan',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-trash',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 17,
                'created_at' => '2020-06-26 04:13:45',
                'updated_at' => '2020-06-26 04:13:45',
                'route' => 'voyager.retur-penjualan.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Retur Penjualan Details',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-trash',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 18,
                'created_at' => '2020-06-26 04:22:41',
                'updated_at' => '2020-06-26 07:23:51',
                'route' => 'voyager.retur-penjualan-details.index',
                'parameters' => 'null',
            ),
            19 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Upload Logs',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-logbook',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 19,
                'created_at' => '2020-06-30 05:23:55',
                'updated_at' => '2020-06-30 05:23:55',
                'route' => 'voyager.upload-logs.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}